#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-diffy
Version  : 3.0.7
Release  : 2
URL      : https://rubygems.org/downloads/diffy-3.0.7.gem
Source0  : https://rubygems.org/downloads/diffy-3.0.7.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
Diffy - Easy Diffing With Ruby [![Build Status](https://secure.travis-ci.org/samg/diffy.png)](http://travis-ci.org/samg/diffy)
============================

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n diffy-3.0.7
gem spec %{SOURCE0} -l --ruby > rubygem-diffy.gemspec

%build
gem build rubygem-diffy.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
diffy-3.0.7.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/diffy-3.0.7
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/diffy-3.0.7.gem
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/cdesc-Diff.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/default_format-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/default_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/diff_bin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/diff_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/each_chunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/string1-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/string2-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/tempfile-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Diff/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Format/cdesc-Format.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Format/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Format/html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Format/html_simple-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/Format/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/cdesc-HtmlFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/clean_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/highlight-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/highlighted_words-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/reconstruct_characters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/split_characters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/wrap_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/HtmlFormatter/wrap_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/Diffy/cdesc-Diffy.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.0.7/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/CHANGELOG
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/CONTRIBUTORS
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/README.md
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/diffy.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/lib/diffy.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/lib/diffy/css.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/lib/diffy/diff.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/lib/diffy/format.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/lib/diffy/html_formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/lib/diffy/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/spec/demo_app.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.0.7/spec/diffy_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/diffy-3.0.7.gemspec
