#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-diffy
Version  : 3.1.0
Release  : 3
URL      : https://rubygems.org/downloads/diffy-3.1.0.gem
Source0  : https://rubygems.org/downloads/diffy-3.1.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
Diffy - Easy Diffing With Ruby [![Build Status](https://travis-ci.org/samg/diffy.svg?branch=master)](https://travis-ci.org/samg/diffy)
============================

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n diffy-3.1.0
gem spec %{SOURCE0} -l --ruby > rubygem-diffy.gemspec

%build
gem build rubygem-diffy.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
diffy-3.1.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/diffy-3.1.0
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/diffy-3.1.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/cdesc-Diff.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/default_format-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/default_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/diff_bin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/diff_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/each_chunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/string1-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/string2-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/tempfile-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Diff/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Format/cdesc-Format.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Format/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Format/html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Format/html_simple-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/Format/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/cdesc-HtmlFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/clean_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/highlight-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/highlighted_words-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/reconstruct_characters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/split_characters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/wrap_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/HtmlFormatter/wrap_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/SplitDiff/cdesc-SplitDiff.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/SplitDiff/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/SplitDiff/split-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/SplitDiff/split_left-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/SplitDiff/split_right-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/Diffy/cdesc-Diffy.ri
/usr/lib64/ruby/gems/2.2.0/doc/diffy-3.1.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/CHANGELOG
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/CONTRIBUTORS
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/diffy.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/lib/diffy.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/lib/diffy/css.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/lib/diffy/diff.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/lib/diffy/format.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/lib/diffy/html_formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/lib/diffy/split_diff.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/lib/diffy/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/spec/demo_app.rb
/usr/lib64/ruby/gems/2.2.0/gems/diffy-3.1.0/spec/diffy_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/diffy-3.1.0.gemspec
